"use client";
import { useEffect,useState } from "react";
import { PageHeader } from "@/components/ui/PageHeader";
import { Card,CardHeader } from "@/components/ui/Card";
import type { CurrencySummary } from "@/lib/revenue-capture/value-summary";
interface FleetOrg {organization:{id:string;name:string;slug:string;plan:string};currencies:CurrencySummary[];pipelineByCurrency:Record<string,number>;opportunityCount:number;riskCount:number;integrations:{total:number;connected:number;unhealthy:number};providers:Array<{provider:string;status:string;health_message?:string|null}>}
interface FleetResponse {operatorRole?:string;organizations?:FleetOrg[];error?:string}
function money(cents:number,currency:string){return new Intl.NumberFormat("en-US",{style:"currency",currency,maximumFractionDigits:0}).format(cents/100);}
function amounts(values:Record<string,number>){return Object.entries(values).map(([currency,value])=>money(value,currency)).join(" · ")||"No evidence";}
export default function OperationsPage(){const [data,setData]=useState<FleetResponse|null>(null);useEffect(()=>{let cancelled=false;async function load(){try{const response=await fetch("/api/operations/fleet",{cache:"no-store"});const payload=await response.json() as FleetResponse;if(!cancelled)setData(response.ok?payload:{error:payload.error??"Could not load fleet"});}catch{if(!cancelled)setData({error:"Could not load fleet"});}}void load();const timer=window.setInterval(load,30000);return()=>{cancelled=true;window.clearInterval(timer);};},[]);const organizations=data?.organizations??[];return <><PageHeader eyebrow="MAXX Operations" title="Fleet" description="Cross-client health for authorized MAXX operators. Currency and evidence classes remain separate."/>{!data?<Card><p className="text-sm text-muted">Loading fleet…</p></Card>:data.error?<Card><CardHeader title="Operator access unavailable" description={data.error}/></Card>:<div className="space-y-4">{organizations.map((row)=><Card key={row.organization.id}><CardHeader title={row.organization.name} description={`${row.organization.plan} · ${row.opportunityCount} opportunities`}/><div className="grid gap-4 sm:grid-cols-2"><Stat label="Verified net payments" value={amounts(Object.fromEntries(row.currencies.map((c)=>[c.currency,c.totalsCents.VERIFIED])))}/><Stat label="Recovery classifications" value={amounts(Object.fromEntries(row.currencies.map((c)=>[c.currency,c.recoveredCents.VERIFIED])))}/><Stat label="Open pipeline" value={amounts(row.pipelineByCurrency)}/><Stat label="Needs attention" value={String(row.riskCount)}/></div><p className="mt-3 text-xs text-muted">Bookings, recovery and pipeline are non-additive. No incremental revenue is inferred.</p><div className="mt-4 flex flex-wrap gap-2">{row.providers.map((provider)=><span key={provider.provider} className="rounded-full border border-border px-3 py-1 text-xs text-muted">{provider.provider}: {provider.status}{provider.health_message?" · attention":""}</span>)}</div></Card>)}</div>}</>}
function Stat({label,value}:{label:string;value:string}){return <div><p className="text-xs text-muted">{label}</p><p className="font-semibold text-text">{value}</p></div>}
